/**
 * AUTO-GENERATED by @nx-mk/client/codegen
 * Source: D:\DevProjects\my\github\nx-mk\examples\devops-incidents\swagger\openapi.json
 * Hash:   2ad7c428431262a0
 * DO NOT EDIT — regenerate from manifest.json
 */
import { createFetchClient } from '@nx-mk/client/runtime'

const userClient = createFetchClient({ baseUrl: "/api" })

export interface Service {
  id: string
  name: string
  status: "healthy" | "degraded" | "down"
  region: string
  version: string
  dependencies: string[]
  lastDeployedAt: string
}

export interface Assignee {
  id: string
  name: string
  email: string
}

export interface Impact {
  usersAffected: number
  regions: string[]
}

export interface Incident {
  id: string
  title: string
  severity: "sev1" | "sev2" | "sev3"
  state: "open" | "mitigated" | "resolved"
  openedAt: string
  resolvedAt: string
  assignee: {
      id: string
      name: string
      email: string
    }
  impact: {
      usersAffected: number
      regions: string[]
    }
}

export interface HealthCheck {
  name: string
  passed: boolean
  latencyMs: number
  message: string
}

export interface HealthOk {
  status: "pass" | "warn" | "fail"
  checks: {
      name: string
      passed: boolean
      latencyMs: number
      message: string
    }[]
}

export interface HealthError {
  code: "SERVICE_UNAVAILABLE" | "UPSTREAM_TIMEOUT" | "RATE_LIMITED"
  message: string
  retryAfterSeconds: number
  contact: string
}

export interface IncidentNote {
  id: string
  body: string
  createdAt: string
}

export interface NewIncidentNote {
  body: string
}

export const api = {
  services: {
    listServices: (params: {}): Promise<Service[]> => {
      return userClient.fetch('GET', `/services`, params)
    },
  },
  incidents: {
    createIncidentNote: (params: { incidentId: string; body: NewIncidentNote }): Promise<IncidentNote> => {
      return userClient.fetch('POST', `/incidents/${encodeURIComponent(String(params['incidentId']))}/notes`, params)
    },
    listServiceIncidents: (params: { serviceId: string }): Promise<Incident[]> => {
      return userClient.fetch('GET', `/services/${encodeURIComponent(String(params['serviceId']))}/incidents`, params)
    },
  },
  health: {
    getServiceHealth: (params: { name: string }): Promise<HealthOk> => {
      return userClient.fetch('GET', `/services/${encodeURIComponent(String(params['name']))}/health`, params)
    },
  },
} as const
