/**
 * AUTO-GENERATED by @nx-mk/client/codegen
 * Source: D:\DevProjects\my\github\nx-mk\examples\medical-records\swagger\openapi.json
 * Hash:   3cfe48ab7c528d2c
 * DO NOT EDIT — regenerate from manifest.json
 */
import { createFetchClient } from '@nx-mk/client/runtime'

const userClient = createFetchClient({ baseUrl: "/api" })

export interface Contact {
  phone: string
  email: string
}

export interface EmergencyContact {
  name: string
  relation: string
}

export interface Insurance {
  policyNumber: string
  expiryDate: string
}

export interface Patient {
  id: string
  name: string
  birthDate: string
  gender: "male" | "female" | "other"
  bloodType: "A" | "B" | "O" | "AB"
  contact: {
      phone: string
      email: string
    }
  emergencyContact: {
      name: string
      relation: string
    }
  insurance: {
      policyNumber: string
      expiryDate: string
    }
  lastVisitAt: string
  notes: string
}

export interface VitalSigns {
  heartRate: number
  heightCm: number
  weightKg: number
}

export interface Medication {
  name: string
  dosage: string
  prescribed: boolean
}

export interface Visit {
  id: string
  visitAt: string
  department: "cardiology" | "neurology" | "general"
  diagnosis: string
  vitals: {
      heartRate: number
      heightCm: number
      weightKg: number
    }
  medications: {
      name: string
      dosage: string
      prescribed: boolean
    }[]
}

export interface CreatedPatient {
  id: string
  name: string
  createdAt: string
}

export interface NewPatient {
  name: string
  birthDate: string
}

export const api = {
  patients: {
    createPatient: (params: { body: NewPatient }): Promise<CreatedPatient> => {
      return userClient.fetch('POST', `/patients`, params)
    },
    getPatient: (params: { patientId: string }): Promise<Patient> => {
      return userClient.fetch('GET', `/patients/${encodeURIComponent(String(params['patientId']))}`, params)
    },
  },
  visits: {
    listPatientVisits: (params: { patientId: string }): Promise<Visit[]> => {
      return userClient.fetch('GET', `/patients/${encodeURIComponent(String(params['patientId']))}/visits`, params)
    },
  },
} as const
