/**
 * AUTO-GENERATED by @nx-mk/client/codegen
 * Source: D:\DevProjects\my\github\nx-mk\examples\commerce-orders\swagger\openapi.json
 * Hash:   803cdaf8db2e0be4
 * DO NOT EDIT — regenerate from manifest.json
 */
import { createFetchClient } from '@nx-mk/client/runtime'

const userClient = createFetchClient({ baseUrl: "/api" })

export interface Supplier {
  id: string
  name: string
  region: string
}

export interface Product {
  id: string
  sku: string
  name: string
  price: number
  currency: "CNY" | "USD" | "EUR"
  category: string
  tags: string[]
  supplier: {
      id: string
      name: string
      region: string
    }
}

export interface ProductPage {
  items: {
      id: string
      sku: string
      name: string
      price: number
      currency: "CNY" | "USD" | "EUR"
      category: string
      tags: string[]
      supplier: {
          id: string
          name: string
          region: string
        }
    }[]
  total: number
  page: number
  pageSize: number
  hasNext: boolean
}

export interface OrderItem {
  sku: string
  name: string
  unitPrice: number
  quantity: number
  lineTotal: number
}

export interface ShippingAddress {
  line1: string
  line2: string
  city: string
  postalCode: string
  country: string
}

export interface Shipping {
  recipient: string
  address: {
      line1: string
      line2: string
      city: string
      postalCode: string
      country: string
    }
}

export interface Payment {
  method: "alipay" | "wechat" | "card"
  paidAt: string
}

export interface Order {
  id: string
  status: "pending" | "paid" | "shipped" | "completed" | "cancelled"
  placedAt: string
  totalAmount: number
  currency: "CNY" | "USD" | "EUR"
  items: {
      sku: string
      name: string
      unitPrice: number
      quantity: number
      lineTotal: number
    }[]
  shipping: {
      recipient: string
      address: {
          line1: string
          line2: string
          city: string
          postalCode: string
          country: string
        }
    }
  payment: {
      method: "alipay" | "wechat" | "card"
      paidAt: string
    }
}

export interface CreatedOrder {
  id: string
  status: "pending" | "paid" | "shipped" | "completed" | "cancelled"
  totalAmount: number
  placedAt: string
}

export interface NewOrder {
  sku: string
  quantity: number
}

export interface OrderDetail {
  id: string
  status: "pending" | "paid" | "shipped" | "completed" | "cancelled"
  customerName: string
  note: string
}

export const api = {
  products: {
    listProducts: (params: { page?: string; pageSize?: string }): Promise<ProductPage> => {
      return userClient.fetch('GET', `/products`, params)
    },
  },
  orders: {
    createOrder: (params: { body: NewOrder }): Promise<CreatedOrder> => {
      return userClient.fetch('POST', `/orders`, params)
    },
    getOrder: (params: { orderId: string }): Promise<OrderDetail> => {
      return userClient.fetch('GET', `/orders/${encodeURIComponent(String(params['orderId']))}`, params)
    },
    listOrders: (params: {}): Promise<Order[]> => {
      return userClient.fetch('GET', `/orders`, params)
    },
  },
} as const
