/**
 * SDK Codegen —— ApiManifest → typed SDK 文件
 *
 * 落地 docx/plan/nx-mk-plan.md §42.5 SDK-CG1/2
 *
 * 输入：ApiManifest（来自 @nx-mk/manifest-schema）
 * 输出：完整的 TypeScript 文件字符串（types + api 对象 + barrel）
 *
 * 调用形态：
 *   import { generateSdk } from '@nx-mk/client/codegen'
 *   import manifest from './manifest.json' assert { type: 'json' }
 *   const code = generateSdk(manifest)
 *   writeFileSync('generated-sdk.ts', code)
 *
 * 设计要点：
 *   - 单文件输出：types + api 同处一处，避免 import 跨文件
 *   - fetch 通过 @nx-mk/client/runtime 内置的 createFetchClient
 *   - 占位 baseUrl：'/api'（demo app 用 Vite proxy 转发）
 */

import type { ApiEndpoint, ApiManifest } from '@nx-mk/manifest-schema'
import { emitNamedTypes } from './emit-types.js'
import { deriveNamespace, emitEndpoint, type MethodSignature } from './emit-endpoint.js'

export interface GenerateSdkOptions {
  /** 生成的 fetch 路径前缀。默认 '/api'（demo vite proxy 转发） */
  baseUrl?: string
  /** 自定义 client factory 导入路径。默认 '@nx-mk/client/runtime' */
  clientImport?: string
}

export function generateSdk(
  manifest: ApiManifest,
  options: GenerateSdkOptions = {},
): string {
  const baseUrl = options.baseUrl ?? '/api'
  const clientImport = options.clientImport ?? '@nx-mk/client/runtime'

  const typesBlock = emitNamedTypes(manifest.schemas)

  // 端点分组：namespace → signatures
  const groups = new Map<string, Array<{ sig: MethodSignature; endpoint: ApiEndpoint }>>()
  for (const ep of manifest.endpoints) {
    const ns = deriveNamespace(ep)
    const list = groups.get(ns) ?? []
    list.push({ sig: emitEndpoint(ep), endpoint: ep })
    groups.set(ns, list)
  }

  // 排序：保留 manifest.endpoints 出现顺序（按 tag 分组后维持插入序）
  // 这样用户读生成代码时按 manifest 顺序展开，比 alphabetic 更直观
  const sortedNs = Array.from(groups.keys())
  const apiLines: string[] = []

  for (const ns of sortedNs) {
    const items = groups.get(ns)!
    // 同一 namespace 内按 method 字母序
    items.sort((a, b) => a.sig.name.localeCompare(b.sig.name))
    apiLines.push(`  ${ns}: {`)
    for (const { sig } of items) {
      const fetchCall = buildFetchCall(sig, baseUrl)
      // 调用体：`getUser: (params: { id: unknown }): Promise<User> => { ... }`
      apiLines.push(`    ${sig.signature}`)
      apiLines.push(`      return userClient.fetch('${sig.httpMethod}', \`${sig.fetchTemplate}\`, params)`)
      apiLines.push(`    },`)
    }
    apiLines.push(`  },`)
  }

  const factoryName = 'userClient'
  const header = `/**
 * AUTO-GENERATED by @nx-mk/client/codegen
 * Source: ${manifest.source.input}
 * Hash:   ${manifest.source.hash}
 * DO NOT EDIT — regenerate from manifest.json
 */
import { createFetchClient } from '${clientImport}'

const ${factoryName} = createFetchClient({ baseUrl: ${JSON.stringify(baseUrl)} })

`

  return [
    header,
    typesBlock,
    '\nexport const api = {\n',
    apiLines.join('\n'),
    '\n} as const\n',
  ].join('')
}

function buildFetchCall(sig: MethodSignature, _baseUrl: string): string {
  // buildFetchCall 是占位——emit-endpoint 已经把 fetch 模板填到 fetchTemplate
  // 这里只做"逻辑校验"
  void sig
  void _baseUrl
  return ''
}
