/**
 * AUTO-GENERATED by @nx-mk/client/codegen
 * Source: ./swagger/openapi.json
 * Hash:   demo
 * DO NOT EDIT — regenerate from manifest.json
 */
import { createFetchClient } from '@nx-mk/client/runtime'

const userClient = createFetchClient({ baseUrl: "/api" })

export interface User {
  id: string
  name: string
  email?: string
  tags?: string[]
  address?: {
      city?: string
      zip?: string
    }
}

export interface Order {
  id?: string
  sku?: string
  quantity?: number
  total?: number
  createdAt?: string
}

export interface NewOrder {
  sku: string
  quantity: number
}

export const api = {
  users: {
    getUser: (params: { id: unknown }): Promise<User> => {
      return userClient.fetch('GET', `/users/${encodeURIComponent(String(params['id']))}`, params)
    },
    listUsers: (params: {}): Promise<unknown> => {
      return userClient.fetch('GET', `/users`, params)
    },
  },
  orders: {
    createOrders: (params: { body: NewOrder }): Promise<Order> => {
      return userClient.fetch('POST', `/orders`, params)
    },
  },
} as const
