/**
 * AUTO-GENERATED by @nx-mk/client/codegen
 * Source: D:\DevProjects\my\github\nx-mk\examples\react-vite-demo\swagger\openapi.json
 * Hash:   3b0170385d9ffdeb
 * DO NOT EDIT — regenerate from manifest.json
 */
import { createFetchClient } from '@nx-mk/client/runtime'

const userClient = createFetchClient({ baseUrl: "/api" })

export interface Address {
  city: string
  zip: string
}

export interface User {
  id: string
  name: string
  email: string
  tags: string[]
  address: {
      city: string
      zip: string
    }
  internalRiskScore?: number
}

export interface Order {
  id: string
  sku: string
  quantity: number
  total: number
  createdAt: string
}

export interface NewOrder {
  sku: string
  quantity: number
}

export const api = {
  users: {
    getUser: (params: { id: string }): Promise<User> => {
      return userClient.fetch('GET', `/users/${encodeURIComponent(String(params['id']))}`, params)
    },
    listUsers: (params: {}): Promise<User[]> => {
      return userClient.fetch('GET', `/users`, params)
    },
  },
  orders: {
    createOrder: (params: { body: NewOrder }): Promise<Order> => {
      return userClient.fetch('POST', `/orders`, params)
    },
  },
} as const
